In [28]:
import numpy as np
import pandas as pd
import scanpy.api as sc

sc.settings.set_figure_params(dpi=80)# verbosity: errors (0), warnings (1), info (2), hints (3)
sc.logging.print_versions()
adata = sc.read("C:/Users/seowjjw/Dropbox/Liver_Paper/Liver10X_76k_Fig1/data/Liver10X_73k.h5ad")

scanpy==1.4 anndata==0.6.19 numpy==1.15.4 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.20.1 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1

In [23]:
#adata = sc.read("C:/Users/seowjjw/Dropbox/Liver_Paper/Liver10X_76k_Fig1/data/Liver10X_73k.h5ad")
adata = sc.read_10x_mtx(
    "C:/Users/seowjjw/Dropbox/Liver_Paper/Liver10X_76k_Fig1/data/GRCh38/",  # the directory with the `.mtx` file
    var_names='gene_symbols',                  # use gene symbols for the variable names (variables-axis index)
    cache=True)

In [2]:
adataX = pd.DataFrame(adata.raw.X.todense(), index = adata.obs.index, 
                      columns = adata.raw.var.index).transpose()

print('No. of cells: ', adataX.shape[1])
print('No. of genes: ', adataX.shape[0])
adataX.head()

No. of cells:  73589
No. of genes:  19852

index,AAACCTGGTCGGGTCT-1,AAAGCAAGTTCGAATC-1,AACCATGAGTAATCCC-1,AACCGCGAGCTCCTCT-1,AACCGCGCACATGTGT-1,AACGTTGAGACGCTTT-1,AACGTTGTCTAACGGT-1,AACTCCCAGCCTATGT-1,AACTCTTCATTACGAC-1,AACTCTTGTCAATGTC-1,...,TTTCCTCGTACGACCC-58,TTTGCGCCACTGTTAG-58,TTTGCGCGTAAACGCG-58,TTTGCGCTCGACAGCC-58,TTTGCGCTCGTAGGAG-58,TTTGGTTTCCGCATCT-58,TTTGGTTTCTTCAACT-58,TTTGTCAAGGATGCGT-58,TTTGTCATCGAATGCT-58,TTTGTCATCTGTGCAA-58
index,,,,,,,,,,,,,,,,,,,,,
RP11-34P13.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
FO538757.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
AP006222.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.693147,0.0
RP4-669L17.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
RP11-206L10.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [3]:
adataX.to_csv('./data/Liv73kexpr.csv')

In [15]:
df = pd.DataFrame(adata.obsm.X_umap, index = adata.obs.index, 
                  columns = ['UMAP_x','UMAP_y'])#.to_csv('C:/Users/seowjjw/Dropbox/Liver_Paper/Garnett/Umapcoord.csv')
df[['louvain','NormalvsTumor','patientno']] = adata.obs[['louvain','NormalvsTumor','patientno']]
display(df.head())

df.to_csv('./data/Liv73k_phenodata.csv')

                      UMAP_x    UMAP_y louvain NormalvsTumor patientno
index
AAACCTGGTCGGGTCT-1  1.017582 -5.641973       4             N        P1
AAAGCAAGTTCGAATC-1  3.080715 -2.566429       0             N        P1
AACCATGAGTAATCCC-1 -3.970394 -3.015633       9             N        P1
AACCGCGAGCTCCTCT-1 -0.116744 -3.645362       4             N        P1
AACCGCGCACATGTGT-1  5.378286 -3.111821       0             N        P1

In [29]:
#adata.raw.var['gene_short_name'] = adata.raw.var.index.tolist()
df = pd.DataFrame(adata.raw.var.index.tolist(), index = adata.raw.var.index.tolist(), columns = ['gene_short_name'])
display(df.head())

              gene_short_name
RP11-34P13.7     RP11-34P13.7
FO538757.2         FO538757.2
AP006222.2         AP006222.2
RP4-669L17.10   RP4-669L17.10
RP11-206L10.9   RP11-206L10.9

In [31]:
import mygene 
mg = mygene.MyGeneInfo()

geneSyms = mg.querymany(df.gene_short_name , scopes='symbol', fields='ensembl.gene', species='human')

geneSyms = pd.DataFrame(geneSyms)
geneSyms = geneSyms[['query','ensembl']]
geneSyms = geneSyms[geneSyms.ensembl.notna()]
ensid = []
for x in geneSyms.ensembl:
    if type(x) is dict:
        ensid.extend(list(x.values()))
    elif type(x) is list:
        ensid.extend(list(x[1].values()))
        
geneSyms['ensid'] = ensid
geneSyms = geneSyms[~geneSyms['query'].duplicated()]

geneSyms.head()

querying 1-1000...done.
querying 1001-2000...done.
querying 2001-3000...done.
querying 3001-4000...done.
querying 4001-5000...done.
querying 5001-6000...done.
querying 6001-7000...done.
querying 7001-8000...done.
querying 8001-9000...done.
querying 9001-10000...done.
querying 10001-11000...done.
querying 11001-12000...done.
querying 12001-13000...done.
querying 13001-14000...done.
querying 14001-15000...done.
querying 15001-16000...done.
querying 16001-17000...done.
querying 17001-18000...done.
querying 18001-19000...done.
querying 19001-19852...done.
Finished.
1091 input query terms found dup hits:
	[('FAM87B', 2), ('LINC00115', 2), ('FAM41C', 2), ('TP73-AS1', 2), ('LINC01134', 2), ('LINC00337', 2)
3330 input query terms found no hit:
	['RP11-34P13.7', 'FO538757.2', 'AP006222.2', 'RP4-669L17.10', 'RP11-206L10.9', 'RP11-54O7.17', 'RP11
Pass "returnall=True" to return complete lists of duplicate or missing query terms.

        query                      ensembl            ensid
5      FAM87B  {'gene': 'ENSG00000177757'}  ENSG00000177757
7   LINC00115  {'gene': 'ENSG00000225880'}  ENSG00000225880
9      FAM41C  {'gene': 'ENSG00000230368'}  ENSG00000230368
11     SAMD11  {'gene': 'ENSG00000187634'}  ENSG00000187634
12      NOC2L  {'gene': 'ENSG00000188976'}  ENSG00000188976

In [55]:
geneSyms.index = geneSyms['query']
df['ensemblid'] = geneSyms['ensid']
df  = df.loc[~df.ensemblid.isna(),]
display(df.head())
display(df.shape)

df.to_csv('./data/Liv73k_featuredata.csv')

          gene_short_name        ensemblid
FAM87B             FAM87B  ENSG00000177757
LINC00115       LINC00115  ENSG00000225880
FAM41C             FAM41C  ENSG00000230368
SAMD11             SAMD11  ENSG00000187634
NOC2L               NOC2L  ENSG00000188976

(16464, 2)

In [20]:
from scipy import sparse, io

m = sparse.csr_matrix(adataX.values)
display(m)              
io.mmwrite("./data/Liv73k_expr.mtx", m)

<19852x73589 sparse matrix of type '<class 'numpy.float32'>'
	with 49756428 stored elements in Compressed Sparse Row format>